# Generated by Django 4.1.7 on 2023-03-25 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import librarian.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='', max_length=100)),
                ('author_name', models.CharField(default='', max_length=100)),
                ('isbn_no', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=20)),
                ('total_copies', models.PositiveIntegerField(default=0)),
                ('available_copies', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('id_no', models.IntegerField(default=0)),
                ('contact_no', models.CharField(default='', max_length=15)),
                ('email_id', models.EmailField(default='', max_length=50)),
                ('no_of_issued_books', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_return_date', models.DateField(default=datetime.datetime.today)),
                ('fine_amount', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.member')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=datetime.datetime.today)),
                ('expected_return_date', models.DateField(default=librarian.models.get_expected_return_date)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.member')),
            ],
        ),
    ]
