# Generated by Django 4.1.7 on 2023-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_member_no_of_issued_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_no',
            field=models.CharField(default='', max_length=50, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='no_of_issued_books',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
